### ISSUE TITLE
Relicense under MPLv2

### ISSUE THREAD

**Issue by helgee** [JuliaAstro/AstroBase.jl#42]
AstroBase.jl, as is, already contains quite a few "derivative works", i.e. ports of BSD-licensed code, while AstroBase itself is MIT-licensed. That does not work because MIT is more permissive than BSD (see [here](https://en.wikipedia.org/wiki/License_compatibility)). While the jury is still out on whether a port is actually a derivative work, I would much rather err on the side of caution and become compliant!

Since I expect the influx of more ports with various licenses, I would choose a license which is compatible with most others (excluding GPL of course 🤷‍♂). The Mozilla Public License v2 (MPLv2) fulfills these requirements: https://choosealicense.com/licenses/mpl-2.0/

Dear contributors,

Could you please indicate by commenting here whether you agree to a license change to MPLv2?

Cheers,
Helge

# Contributors

- [x] @prakharcode has agreed
- [x] @matzipan has agreed
- [ ] @timholy has agreed

**Comment by matzipan** [comment]
Agree to relicense my work as MPLv2.

Andrei Zisu

**Comment by prakharcode** [comment]
Agree to license change.

**Comment by helgee** [comment]
While I have not heard back from Tim, I will go ahead with this. His single commit was a temporary workaround that just moved two lines of code around and thus does not fulfill the originality requirement for being copyrightable.

**Comment by helgee** [comment]
See here for example: https://github.com/JuliaAstro/AstroBase.jl/blob/master/src/earth_attitude/nutation.jl#L8
